### ISSUE TITLE
FEATURE | Add the exit option in the installation script.

### ISSUE THREAD

**Issue by airvzxf** [shuru-project/shuru#19]
# FEATURE

## Description

Add the exit option to the installation script. As a user, I want to select an option to exit rather than do the “hacked” or “technical exit” with CTR+C.

### Output

```text
Please select an option:
1) Install
2) Re-install
3) Uninstall
Enter your choice [1-3]: CTR+c
```

### Expected

```text
Please select an option:
1) Install
2) Re-install
3) Uninstall
4) Exit
Enter your choice [1-4]: 4
```

**Comment by airvzxf** [comment]
Done, thank you.

**Comment by harshdoesdev** [comment]
Hi @airvzxf! Thanks for adding this feature to the install script. It makes it more accessible and less hacky.
