### ISSUE TITLE
FEATURE | Improve custom error output

### ISSUE THREAD

**Issue by airvzxf** [shuru-project/shuru#30]
# FEATURE

## CONTEXT

Custom error output is currently displayed on a single line, and it is separated by the pipe symbol “|”.

## GOAL

Create an output where each error is separated by new lines, adding four whitespace at the beginning. Each line will have a subtitle indicating what type of output is being discussed, whether it is the description or the raw error output.

## CURRENTLY

These are the real examples, every line is one type of error. These follow the next structure: “_Error: General error | Specific error | Technical error_”.
```text
Error: Version manager error | Failed to download version from 'www.fake.com' | builder error
Error: Version manager error | Failed to download Python from 'https://www.python.org/ftp/python/3.10.2/Python-3.10.2.tgz.fake' | Status: 404 Not Found
Error: Version manager error | Failed to create download file '/home/wolf/.shuru/python/3.10.2/python.tgz' | Permission denied (os error 13)
Error: Version manager error | Failed to run command 'cd "/home/wolf/.shuru/python/3.10.2/Python-3.10.2" && "./configurex" "--prefix=/home/wolf/.shuru/python/3.10.2/install"' | No such file or directory (os error 2)
Error: Version manager error | Python build command failed | Exit code: 1
Error: Version manager error | Python build command failed | Exit code: 1 > configure: error: unrecognized option: `-abcdef'
Error: Version manager error | Failed to remove downloaded archive '/home/wolf/.shuru/python/3.10.2/python.tgz/xxx' | Not a directory (os error 20)
```

There are other types of errors which return two errors. In the below example, the format is “_Error: General error | Specific error | General error | Specific error | Technical error_”
```text
Error: Version manager error | Failed to extract archive '/home/wolf/.shuru/python/3.10.2/python.tgz' to '/home/wolf/.shuru/python/3.10.2' | Command execution error | Failed to open tar.gz file | Permission denied (os error 13)
```

### When it throws one error.

```text
Error: Version manager error
    Description: Failed to remove downloaded archive '/home/wolf/.shuru/python/3.10.2/python.tgz/xxx'
    Technical: Not a directory (os error 20)
```

```text
Error: Version manager error
    Description: Failed to download Python from 'https://www.python.org/ftp/python/3.10.2/Python-3.10.2.tgz.fake'
    Technical: Status: 404 Not Found
```

### Special cases when the error throws two technical outputs.

```text
Error: Version manager error
    Description: Python build command failed
    Technical: Exit code: 1
    Technical: configure: error: unrecognized option: `-abcdef'
```
### Cases where it throws two errors.

```text
Error: Version manager error
    Description: Failed to extract archive '/home/wolf/.shuru/python/3.10.2/python.tgz' to '/home/wolf/.shuru/python/3.10.2'
Error: Command execution error
    Description: Failed to open tar.gz file
    Technical: Permission denied (os error 13)
```

## DEVELOPERS

The file for the errors is in `src/error.rs`. The errors are in `pub enum VersionManagerError`.

The implementation of these errors are in two files:
* `src/version_manager/python_version_manager.rs`.
* `src/version_manager/node_version_manager.rs`.

### TIP:

The resolution of this problem could be a little easy. In theory, only needs to add four spaces in the error file. 

## NOTE

This feature was discussed in this post: https://github.com/shuru-project/shuru/discussions/29.

**Comment by airvzxf** [comment]
Hi, @andcscott. I removed the block, you can work on this issue.

**Comment by andcscott** [comment]
Hi @airvzxf, I wrote the implementation today and testing now - hoping to push this weekend. Just a quick question when you have the time: it looks like some errors such as `CommandNameValidationError` and `HttpError` aren't called from anywhere in the rest of the program. How would you like me to handle those?

At the moment I've just formatted the errors the same as the others in the event they're needed in the future. For example:
```
#[error("HTTP error\n    Technical: {0}")]
HttpError(#[from] reqwest::Error),
```

**Comment by airvzxf** [comment]
Yes, @andcscott. Just format the errors, don't clean up or remove errors. You have an eagle eye, thank you for bringing to the conversation.

@harshdoesdev owns the project, and he created for some reason.

**Comment by harshdoesdev** [comment]
Hi @andcscott, thanks for pointing this out. The `CommandNameValidationError` can be removed, as it is no longer used. The `HTTPError` was included for prototyping and can also be removed for now.

**Comment by andcscott** [comment]
Hi @harshdoesdev, I understand, and thanks for your input!
