### ISSUE TITLE
FEATURE | Add version command in Python example

### ISSUE THREAD

**Issue by airvzxf** [shuru-project/shuru#36]
# FEATURE

## DESCRIPTION
Add the version command in the Python example.

## DEVELOPERS
In the file `examples/simple-python-app/shuru.toml`, it needs to add the command version.

```rust
[tasks.version]
command = "python --version"
```

**Comment by airvzxf** [comment]
Hi, @andcscott. This issue is effortless; in the developers' comments is the answer to what it needs to perform.

Are you still interested in contributing to Shuru?

NOTE: Right now, we have a bug which is breaking the app since version 0.0.22, it is easy to perform but needs to fix the bug first.

**Comment by andcscott** [comment]
Hi @airvzxf yes absolutely, thank you for offering. I was about to logout for the day, but I'll go ahead and push something in a few minutes :)
