### ISSUE TITLE
BUG | Unknown version command. Introduced in v0.0.23

### ISSUE THREAD

**Issue by airvzxf** [shuru-project/shuru#40]
# BUG

## DESCRIPTION

In version [0.0.23](https://github.com/shuru-project/shuru/compare/0.0.22...0.0.23) an error was introduced, it didn't recognize the version key which specifies the Python or Node version (`shuru.toml`).

```text
Error: Configuration loading error: Invalid config file format: Unknown version command for key `versions` at line 33 column 1
```

## NOTE

The version 0.0.24 is not working either.

**Comment by harshdoesdev** [comment]
Thanks @airvzxf! This has been resolved in 0.25.

commit: https://github.com/shuru-project/shuru/commit/8c31b88567fe09f8809473a7f8011a8d63c0af0f
