### ISSUE TITLE
Good First Issue: Add More Examples for Python and Node Projects

### ISSUE THREAD

**Issue by harshdoesdev** [shuru-project/shuru#5]
#### Background
To make it easier for new users to get started with Shuru, we need more example configurations for both Python and Node.js projects. Currently, the examples are minimal, and adding more detailed, real-world examples would help developers understand how to use Shuru effectively.

#### Task
1. **Add a Python Project Example**: Include a configuration file (`shuru.toml`) and sample tasks for a typical Python project (e.g., using virtualenv, running tests, etc.).
2. **Add a Node.js Project Example**: Create a more detailed example for a Node.js project, including common tasks such as linting, running tests, and building production code.
3. **Document These Examples**: Update the README or create a new file that explains the new examples and how to use them.

#### Steps to Complete:
1. Create example Python and Node.js projects in a new `/examples` directory.
2. Write example `shuru.toml` files for each project.
3. Ensure each example is documented with clear instructions for setup and usage.

**Comment by moudgalya1223** [comment]
hello @harshdoesdev  can you give us more details and assign this task to me I can start working immediately thanks

**Comment by harshdoesdev** [comment]
Hi @moudgalya1223, thanks for your interest in contributing to the Shuru project! This issue primarily involves creating `shuru.toml` files that can be used in real-world projects. As you can see, the current examples are quite basic and barebones, lacking configurations for tasks such as testing, linting, etc. Additionally, Shuru supports version management for both Python and Node.js, but the current examples do not fully showcase this feature's potential. As a contributor working on this issue, you will enhance the existing examples and add a few new ones, reflecting how real-world applications can improve their development workflows using Shuru. 

I hope this answers your initial question. Feel free to ask any additional questions or if you need further assistance. You can also join our [Discord community](https://discord.gg/EtZn7EdDdS) to interact with fellow Shuru contributors, share suggestions/feedback for improving Shuru, or ask for help.

**Comment by Aditya-PS-05** [comment]
@harshdoesdev 
Can you assign this task to me?

**Comment by harshdoesdev** [comment]
Hi @Aditya-PS-05, I’m assigning this issue to you. Feel free to ask any questions or reach out if you need assistance. You can also join our [Discord community](https://discord.gg/EtZn7EdDdS) to interact with fellow Shuru contributors, share suggestions or feedback for improving Shuru, or ask for help. Thanks for contributing!

**Comment by Aditya-PS-05** [comment]
@harshdoesdev 
I have added the examples. Please accept my pr.
