### ISSUE TITLE
Good First Issue: Improve README

### ISSUE THREAD

**Issue by harshdoesdev** [shuru-project/shuru#6]
#### Background
The current README file provides an overview of Shuru but lacks depth and polish. To make the project more approachable for new users, the README should be improved with more detailed explanations, usage examples, and a clearer structure.

#### Task
1. **Enhance Project Introduction**: Provide a more comprehensive explanation of what Shuru does and why it’s useful.
2. **Add Usage Examples**: Show clear, step-by-step examples of how to configure and use Shuru for different types of projects (Node.js, Python, etc.).
3. **Improve Installation Instructions**: Ensure the installation steps are clear and easy to follow.
4. **Add Badges**: Include helpful badges (e.g., for CI status, version, license) at the top of the README.

#### Steps to Complete:
1. Update the README with more detailed information and examples.
2. Add badges for status, version, and license if available.
3. Make the usage section more beginner-friendly by explaining each step clearly.

**Comment by prxjwal** [comment]
would love to work on it can u assign me this

**Comment by harshdoesdev** [comment]
Hi @prxjwal, I’ve assigned this task to you. Also, please give the repo a star and join our [Discord server](https://discord.com/channels/1291054795037216853/1291329961705340980) if you need support or want to participate in our Hacktoberfest challenge.

**Comment by harshdoesdev** [comment]
Closed with: https://github.com/shuru-project/shuru/pull/23
