### ISSUE TITLE
Good First Issue: Create Documentation in `/docs` (Markdown)

### ISSUE THREAD

**Issue by harshdoesdev** [shuru-project/shuru#7]
#### Background
Shuru would benefit from dedicated documentation to provide users with more in-depth information on how to use the tool, beyond what's available in the README. Having a `/docs` folder with Markdown files would allow us to organize this information effectively.

#### Task
1. **Create a `/docs` Directory**: Set up a folder to hold the documentation.
2. **Write Detailed Docs**: Include sections like:
   - Getting Started
   - Configuration (`shuru.toml` examples)
   - Node.js Version Manager
   - Python Version Manager
   - Advanced Usage
3. **Organize Content**: Ensure the content is well-organized and easy to navigate.

#### Steps to Complete:
1. Create a new `/docs` folder.
2. Write individual Markdown files for each major section of the documentation.
3. Link these documents from the README and make sure the structure is easy to follow.

**Comment by harshdoesdev** [comment]
Related discussion: https://github.com/harshdoesdev/shuru/discussions/2

**Comment by oyerohabib** [comment]
Well done on this @harshdoesdev , really well written 👏.

**Comment by a-wishie** [comment]
Hello! 

I want to contribute to this, is this still available?

**Comment by harshdoesdev** [comment]
Hi @oyerohabib, I’m assigning this task to @a-wishie so you can focus on the Docsite. @a-wishie, feel free to join our Discord channel if you need any help: https://discord.gg/wrjZmUrm. Thanks a lot for contributing to Shuru. Happy coding!

**Comment by oyerohabib** [comment]
Hi @harshdoesdev. Alright, this is duly noted.

**Comment by a-wishie** [comment]
Acknowledged
