### ISSUE TITLE
Good First Issue: Make the Installer Script More User-Friendly

### ISSUE THREAD

**Issue by harshdoesdev** [shuru-project/shuru#8]
#### Background
The current installer script for Shuru works but could be made more user-friendly by improving the messages, adding better error handling, and ensuring it works smoothly on various platforms. Small improvements like these will make the installation process more pleasant for new users.

#### Task
1. **Improve User Messages**: Ensure the script outputs clear, friendly, and informative messages throughout the installation process.
2. **Add Error Handling**: Catch common issues (e.g., missing dependencies) and provide helpful error messages or instructions.
3. **Cross-Platform Compatibility**: Test the installer on different platforms (Linux, macOS, Windows) and make adjustments if necessary.
4. **Add Progress Indicators**: Consider adding progress bars or other feedback mechanisms to let the user know the installation is proceeding smoothly.

#### Steps to Complete:
1. Review and update the installer script to improve the user experience.
2. Test the script on different platforms to ensure compatibility.
3. Add more informative messages, error handling, and potentially progress indicators.

**Comment by prxjwal** [comment]
Could you assign me this?

**Comment by Aditya-PS-05** [comment]
Hey @harshdoesdev ,
Can you assign this task to me also?

**Comment by prxjwal** [comment]
I am testing it on diff platform once that is done i will submit the changes

**Comment by harshdoesdev** [comment]
Hi @Aditya-PS-05, this issue has already been assigned to @prxjwal. However, I have assigned issue https://github.com/shuru-project/shuru/issues/5 to you. Thank you for expressing your interest in contributing to the Shuru project, and happy coding!

**Comment by harshdoesdev** [comment]
Closed with: https://github.com/shuru-project/shuru/pull/12

**Comment by harshdoesdev** [comment]
Closed with: https://github.com/shuru-project/shuru/pull/12

**Comment by prxjwal** [comment]
@harshdoesdev I am participating in hacktoberfest could u label this is as hacktoberfest-accepted
