### ISSUE TITLE
Create Documentation Site Using Next.js

### ISSUE THREAD

**Issue by harshdoesdev** [shuru-project/shuru#9]
### Create Documentation Site Using Next.js

**Background**  
As part of our ongoing efforts to improve the user experience for Shuru, we want to build a dedicated documentation site. This site will provide users with a comprehensive and easy-to-navigate resource for understanding how to effectively use Shuru, building upon the content available in the `/docs` folder (https://github.com/harshdoesdev/shuru/issues/7).

**Task**  
Develop a static documentation site using **Next.js** that pulls in the Markdown files from the `/docs` folder. The site should be visually appealing, responsive, and user-friendly, and it should be deployable on GitHub Pages.

**Requirements:**
1. **Set Up Next.js Project**: Create a new Next.js project for the documentation site.
2. **Integrate Markdown**: Implement functionality to read Markdown files from the `/docs` folder and render them as pages on the site.
3. **Organize Documentation**: Create a structured layout that reflects the organization of the Markdown files, with links to:
   - Getting Started
   - Configuration (shuru.toml examples)
   - Node.js Version Manager
   - Python Version Manager
   - Advanced Usage
4. **Navigation**: Ensure that users can easily navigate between sections of the documentation, including a clear sidebar or menu for quick access.
5. **Styling**: Apply basic styling to make the documentation visually appealing and consistent with the Shuru brand.
6. **Static Site Generation**: Ensure that the site is built as a static site that can be deployed on GitHub Pages.

**Steps to Complete:**
1. Create a new Next.js project.
2. Install necessary packages for Markdown support (e.g., `next-mdx-remote` or similar).
3. Implement the file reading logic to convert Markdown files into React components.
4. Design and implement a layout that organizes documentation content clearly.
5. Configure the project for static site generation.
6. Deploy the documentation site on GitHub Pages and ensure that it is accessible from the main Shuru repository.

**Comment by oyerohabib** [comment]
Great!

**Comment by harshdoesdev** [comment]
Hi @RonakSurana-2001, yes, we are participating in Hacktoberfest, and this issue is part of it. However, this issue has already been assigned to @oyerohabib, who is currently working on it. We will be posting more “Good First Issues” for Hacktoberfest soon. You can join our [Discord community](https://discord.gg/EtZn7EdDdS) to stay updated. Thank you for your interest in contributing to the Shuru Project!
